# -*- coding: utf-8 -*-
"""pH checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BdWNBgJWSz5l1zS-qIXuQjJ930OKA7sd
"""

# @title pH checker

ph = int(input("Enter ph# here: "))
if ph > 7:
    print("Basic")
elif ph < 7:
    print("Acidic")
else:
    print("Neutral")